---
title: "scRNAseq Simulations"
author: "Shirley Mathur"
date: "2025-09-10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```


```{r load-packages}
#load packages
library(tidyverse)
library(Matrix)
library(MASS)
library(Rcpp)
library(RcppArmadillo)
library(nloptr)
library(numDeriv)
library(PLNmodels)
```

```{r load-functions}
#import functions
source("scrnaseq_project_functions.R")
sourceCpp('scrnaseq_project_cpp_functions.cpp')
```


## Simulation Settings
```{r sim-setup}
#set fixed parameter values
set.seed(12)

#set number of samples
n <- 100
#set number of timepoints per sample
m <- 5
#set number of categories
J <- 2

#set VAR(1) noise covariance(Sigma), VAR coefficient matrix (A)
Sigma <- diag(0.5, nrow = J, ncol = J) 
A <- matrix(0.2, 2,2)
#A = matrix(c(0.1,0.5,0.3,0.7),2,2)
#A <- sparseMatrix(i = 1:J, j = sample(1:J, J), x = 0.5, dims = c(J,J))
#A <- diag(0.5, nrow = J, ncol = J)
Sigma_Z <- matrix(solve(diag(1, J*J, J*J) - kronecker(A, A)) %*% c(Sigma),
       nrow = J, ncol = J)


#Set mean offset in parameters of Poisson distribution for observed values
#mu <- matrix(runif(J), nrow = J, ncol = 1)
#mu <- matrix(rep(1.5,J), nrow = J)
mu <- matrix(rep(0.5, J), nrow = J)

#setup for simulation
nsim <- 1000
elbo2 <- TRUE #determine if ELBO based on likelihood conditional on first timepoint or not will be used (will be used if TRUE)
if (elbo2) {full_params <- c("mu", "Sigma", "A")} else { full_params <- c("mu", "Sigma_Z", "A") }
skip_params <- NA

sample_list <- vector(mode = "list")
sim_mu_results <- array(NA, dim = c(3,2,nsim),
                     dimnames = list("est_method" = c("mom", "vi", "chiquet"),
                                  "est" = c("mu1", "mu2"),
                                  "iter" = 1:nsim))

sim_Sigma_Z_results <- array(NA, dim = c(2,4,nsim),
                        dimnames = list("est_method" = c("mom", "vi"),
                                        "est" = c("SZ_11", "SZ_21", "SZ_12", "SZ_22"),
                                        "iter" = 1:nsim))

sim_Sigma_results <- array(NA, dim = c(3,4,nsim),
                        dimnames = list("est_method" = c("mom", "vi", "chiquet"),
                                        "est" = c("Sigma_11", "Sigma_21", "Sigma_12", "Sigma_22"),
                                        "iter" = 1:nsim))

sim_A_results <- array(NA, dim = c(2,4,nsim),
                             dimnames = list("est_method" = c("mom", "vi"),
                                             "est" = c("A_11", "A_21", "A_12", "A_22"),
                                             "iter" = 1:nsim))

A_max_eig_mod <- rep(NA, nsim)

sim_Sigma_list <- vector(mode = "list")
sim_Sigma_pd <- rep(NA, nsim)

sim_M_list <- vector(mode = "list")
sim_S_list <- vector(mode = "list")

#for saving sim settings
sim_settings <- list("n" = n,
                     "m" = m,
                     "J" = J,
                     "nsim" = nsim,
                     "mu" = mu,
                     "Sigma_Z" = Sigma_Z,
                     "A" = A,
                     "opt_params" = setdiff(full_params, skip_params))
```


* Sample size (n): `r n`
* Number of timepoints (m): `r m`
* Dimension of outcome (J): `r J`
* Number of simulation runs: `r nsim`
* Parameters optimized over: `r setdiff(full_params, skip_params)`
* ELBO Utilized: `r if_else(elbo2, "Conditional on Z_1", "Original")`


## Simulation Results
```{r run-sims, eval = FALSE}
for (i in 1:nsim) {
  #generate sample data
  temp_sample <- sim_data(n, m, J, Sigma, A, mu)
  sample_list[[i]] <- temp_sample
  
  #COMPUTE MoM ESTIMATORS and store result
  mom_estimates <- mom_estimator(temp_sample$Y)
  sim_mu_results["mom", ,paste0(i)] <- mu_hat <- mom_estimates$mu_hat
  sim_Sigma_Z_results["mom", ,paste0(i)] <- Sigma_Z_hat_vec <- c(mom_estimates$Sigma_Z_hat)
  sim_Sigma_results["mom", , paste0(i)] <- Sigma_hat_vec <- c(mom_estimates$Sigma_hat)
  sim_A_results["mom", ,paste0(i)] <- A_hat_vec <- c(mom_estimates$A_hat)
  
  #COMPUTE VI ESTIMATES and store result
  if (!elbo2) {
    vi_est <- vi_estimator(temp_sample, 
                         init_mu = mu_hat, 
                         init_Sigma_Z = Sigma_Z_hat_vec,
                         init_A = A_hat_vec,
                         init_M = rep(0, m*J*n),
                         init_S = rep(1, m*J*n),
                         optim_method = "nloptr",
                         max.iter = 100,
                         skip_coords = skip_params)
    
    sim_Sigma_Z_results["vi", ,paste0(i)] <- c(vi_est$Sigma_Z)
    
  } else {
    vi_est_init <- vi_estimator2(temp_sample,
                         init_mu = mu_hat,
                         init_Sigma = Sigma_hat_vec,
                         init_A = A_hat_vec,
                         init_M = rep(0, m*J*n),
                         init_S = rep(1, m*J*n),
                         optim_method = "nloptr",
                         max.iter = 100,
                         skip_coords = full_params)

    M_fix <- c(vi_est_init$M)
    S_fix <- c(vi_est_init$S)

    vi_est <- vi_estimator2(temp_sample, 
                         init_mu = mu_hat, 
                         init_Sigma = Sigma_hat_vec,
                         init_A = A_hat_vec,
                         init_M = M_fix,
                         init_S = S_fix,
                         optim_method = "nloptr",
                         max.iter = 100,
                         tol = 1e-8,
                         skip_coords = c("M", "S", skip_params))
    
    sim_Sigma_results["vi", ,paste0(i)] <- c(vi_est$Sigma)
    sim_M_list[[i]] <- vi_est$M
    sim_S_list[[i]] <- vi_est$S
  }
  
  
  sim_mu_results["vi", ,paste0(i)] <- vi_est$mu
  sim_A_results["vi", ,paste0(i)] <- c(vi_est$A)
  A_max_eig_mod[i] <- max(Mod(eigen(vi_est$A)$values))
  
}
```

```{r run-sims-chiquet}
for (i in 1:nsim) {
  #generate sample data
  temp_sample <- sim_data(n, m, J, Sigma, A, mu)
  sample_list[[i]] <- temp_sample
  
  #prepare it so you can fit PLN model to it
  temp_list <- list("counts" = cbind(c(temp_sample$Y[,1,]), c(temp_sample$Y[,2,])),
                    "covariates" = matrix(1, nrow = m*n, ncol = 1))
  
  rownames(temp_list$counts) <- rownames(temp_list$covariates) <- c(1:(m*n))
  colnames(temp_list$counts) <- c("Y1", "Y2")
  
  temp_prep_data <- prepare_data(temp_list$counts, temp_list$covariates)

  
  #COMPUTE MoM ESTIMATORS and store result
  mom_estimates <- mom_estimator(temp_sample$Y)
  sim_mu_results["mom", ,paste0(i)] <- mu_hat <- mom_estimates$mu_hat
  sim_Sigma_Z_results["mom", ,paste0(i)] <- Sigma_Z_hat_vec <- c(mom_estimates$Sigma_Z_hat)
  sim_Sigma_results["mom", , paste0(i)] <- Sigma_hat_vec <- c(mom_estimates$Sigma_hat)
  sim_A_results["mom", ,paste0(i)] <- A_hat_vec <- c(mom_estimates$A_hat)
  
  #COMPUTE VI ESTIMATES and store result
  if (!elbo2) {
    vi_est <- vi_estimator(temp_sample, 
                         init_mu = mu_hat, 
                         init_Sigma_Z = Sigma_Z_hat_vec,
                         init_A = A_hat_vec,
                         init_M = rep(0, m*J*n),
                         init_S = rep(1, m*J*n),
                         optim_method = "nloptr",
                         max.iter = 100,
                         skip_coords = skip_params)
    
    sim_Sigma_Z_results["vi", ,paste0(i)] <- c(vi_est$Sigma_Z)
    
  } else {
    # vi_est_init <- vi_estimator2(temp_sample,
    #                      init_mu = mu_hat,
    #                      init_Sigma = Sigma_hat_vec,
    #                      init_A = A_hat_vec,
    #                      init_M = rep(0, m*J*n),
    #                      init_S = rep(1, m*J*n),
    #                      optim_method = "nloptr",
    #                      max.iter = 100,
    #                      skip_coords = full_params)
    # 
    # M_fix <- c(vi_est_init$M)
    #S_fix <- c(vi_est_init$S)

    vi_est <- vi_estimator2(temp_sample, 
                         init_mu = mu_hat, 
                         init_Sigma = Sigma_hat_vec,
                         init_A = A_hat_vec,
                         init_M = rep(0, m*J*n),
                         init_S = rep(1, m*J*n),
                         optim_method = "nloptr",
                         max.iter = 100,
                         tol = 1e-8,
                         skip_coords = skip_params)
    
    sim_Sigma_results["vi", ,paste0(i)] <- c(vi_est$Sigma)
    sim_M_list[[i]] <- vi_est$M
    sim_S_list[[i]] <- vi_est$S
  }
  
  
  sim_mu_results["vi", ,paste0(i)] <- vi_est$mu
  sim_A_results["vi", ,paste0(i)] <- c(vi_est$A)
  A_max_eig_mod[i] <- max(Mod(eigen(vi_est$A)$values))
  
  #COMPUTE PLN ESTIMATES AND STORE RESULT
  pln_fit <- PLN(Abundance ~ 1, temp_prep_data)
  sim_mu_results["chiquet", ,paste0(i)] <- c(pln_fit$model_par$Theta)
  sim_Sigma_results["chiquet",,paste0(i)] <- c(pln_fit$model_par$Sigma)
  
}
```

```{r report-results}
#save results
save(sim_settings, sim_mu_results, sim_A_results, sim_Sigma_results, sim_Sigma_Z_results, A_max_eig_mod, sim_M_list, sim_S_list, sample_list, file = "all_params_cond_elbo_compare_chiquet_sim.Rdata")
#tabulate results
sim_res_df <- as.data.frame.table(sim_mu_results, responseName = "value")
sim_SZ_res_df <- as.data.frame.table(sim_Sigma_Z_results, responseName = "value")
sim_A_res_df <- as.data.frame.table(sim_A_results, responseName = "value")
sim_Sigma_res_df <- as.data.frame.table(sim_Sigma_results, responseName = "value")

#data frame of mu results
mu_summary <- sim_res_df %>% group_by(est_method, est) %>%
  summarise(mean_val = mean(value),
            median_val = median(value),
            sd = sd(value)) %>%
  mutate(true_val = if_else(est == "mu1", mu[1], mu[2])) %>%
  relocate(true_val, .before = mean_val)

#data frame of Sigma_Z results
sigma_Z_summary <- sim_SZ_res_df %>% group_by(est_method, est) %>%
  summarise(mean_val = mean(value),
            median_val = median(value),
            sd = sd(value)) %>%
  mutate(true_val = case_when(est == "SZ_11" ~ Sigma_Z[1,1],
                              est == "SZ_12" ~ Sigma_Z[1,2],
                              est == "SZ_21" ~ Sigma_Z[2,1],
                              est == "SZ_22" ~ Sigma_Z[2,2])) %>%
  relocate(true_val, .before = mean_val)

#data frame of Sigma results
sigma_summary <- sim_Sigma_res_df %>% group_by(est_method, est) %>%
  summarise(mean_val = mean(value),
            median_val = median(value),
            sd = sd(value)) %>%
  mutate(true_val = case_when(est == "Sigma_11" ~ Sigma[1,1],
                              est == "Sigma_12" ~ Sigma[1,2],
                              est == "Sigma_21" ~ Sigma[2,1],
                              est == "Sigma_22" ~ Sigma[2,2])) %>%
  relocate(true_val, .before = mean_val)

#data frame of A results
A_summary <- sim_A_res_df %>% group_by(est_method, est) %>%
  summarise(mean_val = mean(value),
            median_val = median(value),
            sd = sd(value)) %>%
  mutate(true_val = case_when(est == "A_11" ~ A[1,1],
                           est == "A_12" ~ A[1,2],
                           est == "A_21" ~ A[2,1],
                           est == "A_22" ~ A[2,2])) %>%
  relocate(true_val, .before = mean_val)

all_summary <- data.frame()

if (!("mu" %in% skip_params)) {
  all_summary <- rbind(all_summary, mu_summary)
}

if (!("Sigma_Z" %in% skip_params) & !elbo2) {
  all_summary <- rbind(all_summary, sigma_Z_summary)
}

if (!("A" %in% skip_params)) {
  all_summary <- rbind(all_summary, A_summary)
}

if (!("Sigma" %in% skip_params) & elbo2) {
  all_summary <- rbind(all_summary, sigma_summary)
}


all_summary %>% kableExtra::kable(digits = 3, caption = "Summary of Results")

# #plot of mu errors
# png("mu_errors.png", width = 6, height = 6, units = "in", res = 300)
if (!("mu" %in% skip_params)) {
  sim_res_df %>% mutate(error = if_else(est == "mu1", value - mu[1], value - mu[2])) %>%
  ggplot(mapping = aes(x = error)) +
  geom_boxplot() +
  facet_wrap(est_method ~ est, scales = "free") +
  labs(title = "Summary of Errors Across Simulations for mu",
       x = "Error (Est - True)") +
  theme_bw() +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
# dev.off()
}  


# #plot of Sigma_Z errors
if (!("Sigma_Z" %in% skip_params) & !elbo2) {
  # png("Sigma_Z_errors.png", width = 6, height = 6, units = "in", res = 300)
  sim_SZ_res_df %>%
    mutate(error = case_when(est == "SZ_11" ~ value - Sigma_Z[1,1],
                             est == "SZ_12" ~ value - Sigma_Z[1,2],
                             est == "SZ_21" ~ value - Sigma_Z[2,1],
                             est == "SZ_22" ~ value - Sigma_Z[2,2])) %>%
    ggplot(mapping = aes(x = error)) +
    geom_boxplot() +
    facet_grid(est_method ~ est, scales = "free") +
    labs(title = "Summary of Errors Across Simulations for Sigma_Z",
         x = "Error (Est - True)") +
    theme_bw() +
    theme(axis.text.y=element_blank(),
          axis.ticks.y=element_blank())
  
  # dev.off()
}

#plot of A errors
if (!("A" %in% skip_params)) {
  sim_A_res_df %>%
  mutate(error = case_when(est == "A_11" ~ value - A[1,1],
                           est == "A_12" ~ value - A[1,2],
                           est == "A_21" ~ value - A[2,1],
                           est == "A_22" ~ value - A[2,2])) %>%
  ggplot(mapping = aes(x = error)) +
  geom_boxplot() +
  facet_grid(est_method ~ est, scales = "free") +
  labs(title = "Summary of Errors Across Simulations for A",
       x = "Error (Est - True)") +
  theme_bw() +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
}

#plot of Sigma errors
if (!("Sigma" %in% skip_params) & elbo2) {
  sim_Sigma_res_df %>%
  mutate(error = case_when(est == "Sigma_11" ~ value - Sigma_Z[1,1],
                           est == "Sigma_12" ~ value - Sigma_Z[1,2],
                           est == "Sigma_21" ~ value - Sigma_Z[2,1],
                           est == "Sigma_22" ~ value - Sigma_Z[2,2])) %>%
  ggplot(mapping = aes(x = error)) +
  geom_boxplot() +
  facet_wrap(est_method ~ est, scales = "free") +
  labs(title = "Summary of Errors Across Simulations for Sigma",
       x = "Error (Est - True)") +
  theme_bw() +
  theme(axis.text.y=element_blank(),
        axis.ticks.y=element_blank())
}
```


